### ISSUE TITLE
Lasso select

### ISSUE THREAD

**Issue by 3dphoto** [s1pierro/Papier#64]
I know you want the user to select by triangles and they still can. This is providing a faster tool in case user has a dense mesh when selecting many triangles in a given area and/or making Papier smarter. Propose the idea of a lasso.

**Dense mesh**
![image](https://user-images.githubusercontent.com/28678758/41477717-029be48a-707a-11e8-98ae-cf64a54e9031.png)

**Lasso tool**
![3c233d98e156d62a1bd994282bdc25e4533b1cd4](https://user-images.githubusercontent.com/28678758/41477785-3ef0d904-707a-11e8-90d5-980ae5d8d7a3.gif)

I think you can get the idea from what I'm after.

**Comment by s1pierro** [comment]
I anderstand this, and I can perform it, but it is related to an other software than papier right now :)
