### ISSUE TITLE
Program thinks 4 pages exist when shapes fit on 1 page

### ISSUE THREAD

**Issue by 3dphoto** [s1pierro/Papier#71]
**Unless the formula for A1 = 8 pages for A4 that the island would need to be divided to fit on your personal printer?**

**Small paper preview**
![image](https://user-images.githubusercontent.com/28678758/41508539-68649280-71fb-11e8-9000-019ffa52bf72.png)

**Large paper preview**
![image](https://user-images.githubusercontent.com/28678758/41508545-77eb412c-71fb-11e8-872e-466dbf5c9d3f.png)

---

**Reference**
https://github.com/s1pierro/Papier/issues/72 [Program thinks A1 is 8 pages?](https://github.com/s1pierro/Papier/issues/72)

**Comment by s1pierro** [comment]
That s why I put a paper size display in the 3D view.

**Comment by s1pierro** [comment]
duplicate :) #72
